/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ArticleId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Article = IDL.Record({
  'id' : ArticleId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'authorName' : IDL.Text,
  'publishedAt' : Timestamp,
  'category' : IDL.Text,
  'authorPrincipal' : IDL.Principal,
});
export const UserRole = IDL.Variant({
  'DataAnalyst' : IDL.Null,
  'FinancialAdvisor' : IDL.Null,
  'Admin' : IDL.Null,
  'Investor' : IDL.Null,
});
export const AdvisorStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const User = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'role' : UserRole,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'advisorStatus' : IDL.Opt(AdvisorStatus),
  'registrationDate' : Timestamp,
});
export const FundId = IDL.Nat;
export const HistoricalPoint = IDL.Record({
  'nav' : IDL.Float64,
  'date' : IDL.Text,
});
export const FundCategory = IDL.Variant({
  'Debt' : IDL.Null,
  'Balanced' : IDL.Null,
  'MoneyMarket' : IDL.Null,
  'Equity' : IDL.Null,
});
export const RiskLevel = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
});
export const Fund = IDL.Record({
  'id' : FundId,
  'nav' : IDL.Float64,
  'name' : IDL.Text,
  'minInvestment' : IDL.Float64,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'historicalData' : IDL.Vec(HistoricalPoint),
  'category' : FundCategory,
  'inceptionDate' : IDL.Text,
  'managerBio' : IDL.Text,
  'expenseRatio' : IDL.Float64,
  'riskLevel' : RiskLevel,
  'return1Y' : IDL.Float64,
  'return3Y' : IDL.Float64,
  'return5Y' : IDL.Float64,
  'managerName' : IDL.Text,
});
export const FundFilter = IDL.Record({
  'searchText' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(FundCategory),
  'riskLevel' : IDL.Opt(RiskLevel),
});
export const PlatformStats = IDL.Record({
  'totalFunds' : IDL.Nat,
  'activeInvestors' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'pendingAdvisors' : IDL.Nat,
});
export const PostArticleRequest = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'category' : IDL.Text,
});
export const RegisterUserRequest = IDL.Record({
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const UpdateFundRequest = IDL.Record({
  'nav' : IDL.Float64,
  'expenseRatio' : IDL.Float64,
  'riskLevel' : RiskLevel,
  'return1Y' : IDL.Float64,
  'return3Y' : IDL.Float64,
  'return5Y' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'approveAdvisor' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'getArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getCallerUser' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getFavorites' : IDL.Func([], [IDL.Vec(FundId)], ['query']),
  'getFund' : IDL.Func([FundId], [IDL.Opt(Fund)], ['query']),
  'getFunds' : IDL.Func([FundFilter], [IDL.Vec(Fund)], ['query']),
  'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
  'getTopPerformingFunds' : IDL.Func([IDL.Nat], [IDL.Vec(Fund)], ['query']),
  'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'postArticle' : IDL.Func([PostArticleRequest], [Article], []),
  'registerUser' : IDL.Func([RegisterUserRequest], [User], []),
  'rejectAdvisor' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'removeFavorite' : IDL.Func([FundId], [], []),
  'saveFavorite' : IDL.Func([FundId], [], []),
  'toggleUserStatus' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'updateFund' : IDL.Func([FundId, UpdateFundRequest], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ArticleId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Article = IDL.Record({
    'id' : ArticleId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'authorName' : IDL.Text,
    'publishedAt' : Timestamp,
    'category' : IDL.Text,
    'authorPrincipal' : IDL.Principal,
  });
  const UserRole = IDL.Variant({
    'DataAnalyst' : IDL.Null,
    'FinancialAdvisor' : IDL.Null,
    'Admin' : IDL.Null,
    'Investor' : IDL.Null,
  });
  const AdvisorStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const User = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'role' : UserRole,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'advisorStatus' : IDL.Opt(AdvisorStatus),
    'registrationDate' : Timestamp,
  });
  const FundId = IDL.Nat;
  const HistoricalPoint = IDL.Record({
    'nav' : IDL.Float64,
    'date' : IDL.Text,
  });
  const FundCategory = IDL.Variant({
    'Debt' : IDL.Null,
    'Balanced' : IDL.Null,
    'MoneyMarket' : IDL.Null,
    'Equity' : IDL.Null,
  });
  const RiskLevel = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const Fund = IDL.Record({
    'id' : FundId,
    'nav' : IDL.Float64,
    'name' : IDL.Text,
    'minInvestment' : IDL.Float64,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'historicalData' : IDL.Vec(HistoricalPoint),
    'category' : FundCategory,
    'inceptionDate' : IDL.Text,
    'managerBio' : IDL.Text,
    'expenseRatio' : IDL.Float64,
    'riskLevel' : RiskLevel,
    'return1Y' : IDL.Float64,
    'return3Y' : IDL.Float64,
    'return5Y' : IDL.Float64,
    'managerName' : IDL.Text,
  });
  const FundFilter = IDL.Record({
    'searchText' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(FundCategory),
    'riskLevel' : IDL.Opt(RiskLevel),
  });
  const PlatformStats = IDL.Record({
    'totalFunds' : IDL.Nat,
    'activeInvestors' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'pendingAdvisors' : IDL.Nat,
  });
  const PostArticleRequest = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'category' : IDL.Text,
  });
  const RegisterUserRequest = IDL.Record({
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const UpdateFundRequest = IDL.Record({
    'nav' : IDL.Float64,
    'expenseRatio' : IDL.Float64,
    'riskLevel' : RiskLevel,
    'return1Y' : IDL.Float64,
    'return3Y' : IDL.Float64,
    'return5Y' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'approveAdvisor' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'getArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getCallerUser' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getFavorites' : IDL.Func([], [IDL.Vec(FundId)], ['query']),
    'getFund' : IDL.Func([FundId], [IDL.Opt(Fund)], ['query']),
    'getFunds' : IDL.Func([FundFilter], [IDL.Vec(Fund)], ['query']),
    'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
    'getTopPerformingFunds' : IDL.Func([IDL.Nat], [IDL.Vec(Fund)], ['query']),
    'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'postArticle' : IDL.Func([PostArticleRequest], [Article], []),
    'registerUser' : IDL.Func([RegisterUserRequest], [User], []),
    'rejectAdvisor' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'removeFavorite' : IDL.Func([FundId], [], []),
    'saveFavorite' : IDL.Func([FundId], [], []),
    'toggleUserStatus' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'updateFund' : IDL.Func([FundId, UpdateFundRequest], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };