/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AdvisorStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export interface Article {
  'id' : ArticleId,
  'title' : string,
  'content' : string,
  'authorName' : string,
  'publishedAt' : Timestamp,
  'category' : string,
  'authorPrincipal' : Principal,
}
export type ArticleId = bigint;
export interface Fund {
  'id' : FundId,
  'nav' : number,
  'name' : string,
  'minInvestment' : number,
  'description' : string,
  'isActive' : boolean,
  'historicalData' : Array<HistoricalPoint>,
  'category' : FundCategory,
  'inceptionDate' : string,
  'managerBio' : string,
  'expenseRatio' : number,
  'riskLevel' : RiskLevel,
  'return1Y' : number,
  'return3Y' : number,
  'return5Y' : number,
  'managerName' : string,
}
export type FundCategory = { 'Debt' : null } |
  { 'Balanced' : null } |
  { 'MoneyMarket' : null } |
  { 'Equity' : null };
export interface FundFilter {
  'searchText' : [] | [string],
  'category' : [] | [FundCategory],
  'riskLevel' : [] | [RiskLevel],
}
export type FundId = bigint;
export interface HistoricalPoint { 'nav' : number, 'date' : string }
export interface PlatformStats {
  'totalFunds' : bigint,
  'activeInvestors' : bigint,
  'totalUsers' : bigint,
  'pendingAdvisors' : bigint,
}
export interface PostArticleRequest {
  'title' : string,
  'content' : string,
  'category' : string,
}
export interface RegisterUserRequest {
  'name' : string,
  'role' : UserRole,
  'email' : string,
}
export type RiskLevel = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null };
export type Timestamp = bigint;
export interface UpdateFundRequest {
  'nav' : number,
  'expenseRatio' : number,
  'riskLevel' : RiskLevel,
  'return1Y' : number,
  'return3Y' : number,
  'return5Y' : number,
}
export interface User {
  'principal' : Principal,
  'name' : string,
  'role' : UserRole,
  'isActive' : boolean,
  'email' : string,
  'advisorStatus' : [] | [AdvisorStatus],
  'registrationDate' : Timestamp,
}
export type UserRole = { 'DataAnalyst' : null } |
  { 'FinancialAdvisor' : null } |
  { 'Admin' : null } |
  { 'Investor' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'approveAdvisor' : ActorMethod<[Principal], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'getArticles' : ActorMethod<[], Array<Article>>,
  'getCallerUser' : ActorMethod<[], [] | [User]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getFavorites' : ActorMethod<[], Array<FundId>>,
  'getFund' : ActorMethod<[FundId], [] | [Fund]>,
  'getFunds' : ActorMethod<[FundFilter], Array<Fund>>,
  'getPlatformStats' : ActorMethod<[], PlatformStats>,
  'getTopPerformingFunds' : ActorMethod<[bigint], Array<Fund>>,
  'getUsers' : ActorMethod<[], Array<User>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'postArticle' : ActorMethod<[PostArticleRequest], Article>,
  'registerUser' : ActorMethod<[RegisterUserRequest], User>,
  'rejectAdvisor' : ActorMethod<[Principal], boolean>,
  'removeFavorite' : ActorMethod<[FundId], undefined>,
  'saveFavorite' : ActorMethod<[FundId], undefined>,
  'toggleUserStatus' : ActorMethod<[Principal], boolean>,
  'updateFund' : ActorMethod<[FundId, UpdateFundRequest], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];