/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RegisterUserRequest {
    name: string;
    role: UserRole;
    email: string;
}
export type FundId = bigint;
export type Timestamp = bigint;
export interface HistoricalPoint {
    nav: number;
    date: string;
}
export interface User {
    principal: Principal;
    name: string;
    role: UserRole;
    isActive: boolean;
    email: string;
    advisorStatus?: AdvisorStatus;
    registrationDate: Timestamp;
}
export interface PostArticleRequest {
    title: string;
    content: string;
    category: string;
}
export type ArticleId = bigint;
export interface FundFilter {
    searchText?: string;
    category?: FundCategory;
    riskLevel?: RiskLevel;
}
export interface UpdateFundRequest {
    nav: number;
    expenseRatio: number;
    riskLevel: RiskLevel;
    return1Y: number;
    return3Y: number;
    return5Y: number;
}
export interface PlatformStats {
    totalFunds: bigint;
    activeInvestors: bigint;
    totalUsers: bigint;
    pendingAdvisors: bigint;
}
export interface Fund {
    id: FundId;
    nav: number;
    name: string;
    minInvestment: number;
    description: string;
    isActive: boolean;
    historicalData: Array<HistoricalPoint>;
    category: FundCategory;
    inceptionDate: string;
    managerBio: string;
    expenseRatio: number;
    riskLevel: RiskLevel;
    return1Y: number;
    return3Y: number;
    return5Y: number;
    managerName: string;
}
export interface Article {
    id: ArticleId;
    title: string;
    content: string;
    authorName: string;
    publishedAt: Timestamp;
    category: string;
    authorPrincipal: Principal;
}
export enum AdvisorStatus {
    Approved = "Approved",
    Rejected = "Rejected",
    Pending = "Pending"
}
export enum FundCategory {
    Debt = "Debt",
    Balanced = "Balanced",
    MoneyMarket = "MoneyMarket",
    Equity = "Equity"
}
export enum RiskLevel {
    Low = "Low",
    High = "High",
    Medium = "Medium"
}
export enum UserRole {
    DataAnalyst = "DataAnalyst",
    FinancialAdvisor = "FinancialAdvisor",
    Admin = "Admin",
    Investor = "Investor"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    approveAdvisor(principal: Principal): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    getArticles(): Promise<Array<Article>>;
    getCallerUser(): Promise<User | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getFavorites(): Promise<Array<FundId>>;
    getFund(id: FundId): Promise<Fund | null>;
    getFunds(filter: FundFilter): Promise<Array<Fund>>;
    getPlatformStats(): Promise<PlatformStats>;
    getTopPerformingFunds(limit: bigint): Promise<Array<Fund>>;
    getUsers(): Promise<Array<User>>;
    isCallerAdmin(): Promise<boolean>;
    postArticle(req: PostArticleRequest): Promise<Article>;
    registerUser(req: RegisterUserRequest): Promise<User>;
    rejectAdvisor(principal: Principal): Promise<boolean>;
    removeFavorite(fundId: FundId): Promise<void>;
    saveFavorite(fundId: FundId): Promise<void>;
    toggleUserStatus(principal: Principal): Promise<boolean>;
    updateFund(id: FundId, req: UpdateFundRequest): Promise<boolean>;
}
import type { AdvisorStatus as _AdvisorStatus, Fund as _Fund, FundCategory as _FundCategory, FundFilter as _FundFilter, FundId as _FundId, HistoricalPoint as _HistoricalPoint, RegisterUserRequest as _RegisterUserRequest, RiskLevel as _RiskLevel, Timestamp as _Timestamp, UpdateFundRequest as _UpdateFundRequest, User as _User, UserRole as _UserRole, UserRole__1 as _UserRole__1 } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async approveAdvisor(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveAdvisor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveAdvisor(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getArticles(): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticles();
            return result;
        }
    }
    async getCallerUser(): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUser();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUser();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFavorites(): Promise<Array<FundId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFavorites();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFavorites();
            return result;
        }
    }
    async getFund(arg0: FundId): Promise<Fund | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFund(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFund(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFunds(arg0: FundFilter): Promise<Array<Fund>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFunds(to_candid_FundFilter_n20(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFunds(to_candid_FundFilter_n20(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlatformStats(): Promise<PlatformStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformStats();
            return result;
        }
    }
    async getTopPerformingFunds(arg0: bigint): Promise<Array<Fund>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopPerformingFunds(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopPerformingFunds(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async postArticle(arg0: PostArticleRequest): Promise<Article> {
        if (this.processError) {
            try {
                const result = await this.actor.postArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postArticle(arg0);
            return result;
        }
    }
    async registerUser(arg0: RegisterUserRequest): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(to_candid_RegisterUserRequest_n28(this._uploadFile, this._downloadFile, arg0));
                return from_candid_User_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(to_candid_RegisterUserRequest_n28(this._uploadFile, this._downloadFile, arg0));
            return from_candid_User_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectAdvisor(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectAdvisor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectAdvisor(arg0);
            return result;
        }
    }
    async removeFavorite(arg0: FundId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFavorite(arg0);
            return result;
        }
    }
    async saveFavorite(arg0: FundId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveFavorite(arg0);
            return result;
        }
    }
    async toggleUserStatus(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleUserStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleUserStatus(arg0);
            return result;
        }
    }
    async updateFund(arg0: FundId, arg1: UpdateFundRequest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFund(arg0, to_candid_UpdateFundRequest_n32(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFund(arg0, to_candid_UpdateFundRequest_n32(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AdvisorStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdvisorStatus): AdvisorStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_FundCategory_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FundCategory): FundCategory {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Fund_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Fund): Fund {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_RiskLevel_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskLevel): RiskLevel {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_User_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Fund]): Fund | null {
    return value.length === 0 ? null : from_candid_Fund_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AdvisorStatus]): AdvisorStatus | null {
    return value.length === 0 ? null : from_candid_AdvisorStatus_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FundId;
    nav: number;
    name: string;
    minInvestment: number;
    description: string;
    isActive: boolean;
    historicalData: Array<_HistoricalPoint>;
    category: _FundCategory;
    inceptionDate: string;
    managerBio: string;
    expenseRatio: number;
    riskLevel: _RiskLevel;
    return1Y: number;
    return3Y: number;
    return5Y: number;
    managerName: string;
}): {
    id: FundId;
    nav: number;
    name: string;
    minInvestment: number;
    description: string;
    isActive: boolean;
    historicalData: Array<HistoricalPoint>;
    category: FundCategory;
    inceptionDate: string;
    managerBio: string;
    expenseRatio: number;
    riskLevel: RiskLevel;
    return1Y: number;
    return3Y: number;
    return5Y: number;
    managerName: string;
} {
    return {
        id: value.id,
        nav: value.nav,
        name: value.name,
        minInvestment: value.minInvestment,
        description: value.description,
        isActive: value.isActive,
        historicalData: value.historicalData,
        category: from_candid_FundCategory_n16(_uploadFile, _downloadFile, value.category),
        inceptionDate: value.inceptionDate,
        managerBio: value.managerBio,
        expenseRatio: value.expenseRatio,
        riskLevel: from_candid_RiskLevel_n18(_uploadFile, _downloadFile, value.riskLevel),
        return1Y: value.return1Y,
        return3Y: value.return3Y,
        return5Y: value.return5Y,
        managerName: value.managerName
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    name: string;
    role: _UserRole;
    isActive: boolean;
    email: string;
    advisorStatus: [] | [_AdvisorStatus];
    registrationDate: _Timestamp;
}): {
    principal: Principal;
    name: string;
    role: UserRole;
    isActive: boolean;
    email: string;
    advisorStatus?: AdvisorStatus;
    registrationDate: Timestamp;
} {
    return {
        principal: value.principal,
        name: value.name,
        role: from_candid_UserRole_n6(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive,
        email: value.email,
        advisorStatus: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.advisorStatus)),
        registrationDate: value.registrationDate
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Approved: null;
} | {
    Rejected: null;
} | {
    Pending: null;
}): AdvisorStatus {
    return "Approved" in value ? AdvisorStatus.Approved : "Rejected" in value ? AdvisorStatus.Rejected : "Pending" in value ? AdvisorStatus.Pending : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Debt: null;
} | {
    Balanced: null;
} | {
    MoneyMarket: null;
} | {
    Equity: null;
}): FundCategory {
    return "Debt" in value ? FundCategory.Debt : "Balanced" in value ? FundCategory.Balanced : "MoneyMarket" in value ? FundCategory.MoneyMarket : "Equity" in value ? FundCategory.Equity : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
}): RiskLevel {
    return "Low" in value ? RiskLevel.Low : "High" in value ? RiskLevel.High : "Medium" in value ? RiskLevel.Medium : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    DataAnalyst: null;
} | {
    FinancialAdvisor: null;
} | {
    Admin: null;
} | {
    Investor: null;
}): UserRole {
    return "DataAnalyst" in value ? UserRole.DataAnalyst : "FinancialAdvisor" in value ? UserRole.FinancialAdvisor : "Admin" in value ? UserRole.Admin : "Investor" in value ? UserRole.Investor : value;
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Fund>): Array<Fund> {
    return value.map((x)=>from_candid_Fund_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n4(_uploadFile, _downloadFile, x));
}
function to_candid_FundCategory_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FundCategory): _FundCategory {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_FundFilter_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FundFilter): _FundFilter {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_RegisterUserRequest_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegisterUserRequest): _RegisterUserRequest {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_RiskLevel_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskLevel): _RiskLevel {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateFundRequest_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateFundRequest): _UpdateFundRequest {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    searchText?: string;
    category?: FundCategory;
    riskLevel?: RiskLevel;
}): {
    searchText: [] | [string];
    category: [] | [_FundCategory];
    riskLevel: [] | [_RiskLevel];
} {
    return {
        searchText: value.searchText ? candid_some(value.searchText) : candid_none(),
        category: value.category ? candid_some(to_candid_FundCategory_n22(_uploadFile, _downloadFile, value.category)) : candid_none(),
        riskLevel: value.riskLevel ? candid_some(to_candid_RiskLevel_n24(_uploadFile, _downloadFile, value.riskLevel)) : candid_none()
    };
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: UserRole;
    email: string;
}): {
    name: string;
    role: _UserRole;
    email: string;
} {
    return {
        name: value.name,
        role: to_candid_UserRole_n30(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nav: number;
    expenseRatio: number;
    riskLevel: RiskLevel;
    return1Y: number;
    return3Y: number;
    return5Y: number;
}): {
    nav: number;
    expenseRatio: number;
    riskLevel: _RiskLevel;
    return1Y: number;
    return3Y: number;
    return5Y: number;
} {
    return {
        nav: value.nav,
        expenseRatio: value.expenseRatio,
        riskLevel: to_candid_RiskLevel_n24(_uploadFile, _downloadFile, value.riskLevel),
        return1Y: value.return1Y,
        return3Y: value.return3Y,
        return5Y: value.return5Y
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FundCategory): {
    Debt: null;
} | {
    Balanced: null;
} | {
    MoneyMarket: null;
} | {
    Equity: null;
} {
    return value == FundCategory.Debt ? {
        Debt: null
    } : value == FundCategory.Balanced ? {
        Balanced: null
    } : value == FundCategory.MoneyMarket ? {
        MoneyMarket: null
    } : value == FundCategory.Equity ? {
        Equity: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskLevel): {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
} {
    return value == RiskLevel.Low ? {
        Low: null
    } : value == RiskLevel.High ? {
        High: null
    } : value == RiskLevel.Medium ? {
        Medium: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    DataAnalyst: null;
} | {
    FinancialAdvisor: null;
} | {
    Admin: null;
} | {
    Investor: null;
} {
    return value == UserRole.DataAnalyst ? {
        DataAnalyst: null
    } : value == UserRole.FinancialAdvisor ? {
        FinancialAdvisor: null
    } : value == UserRole.Admin ? {
        Admin: null
    } : value == UserRole.Investor ? {
        Investor: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
